# Generated by Django 5.1.5 on 2025-01-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atividade',
            options={'verbose_name': 'Atividade', 'verbose_name_plural': 'Atividades'},
        ),
        migrations.AlterModelOptions(
            name='membro',
            options={'verbose_name': 'Membro', 'verbose_name_plural': 'Membros'},
        ),
        migrations.AlterModelOptions(
            name='projeto',
            options={'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
        migrations.RenameField(
            model_name='atividade',
            old_name='projeto',
            new_name='proejto',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='membro',
        ),
        migrations.AlterField(
            model_name='projeto',
            name='dt_final',
            field=models.DateField(verbose_name='Data final'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='dt_inicial',
            field=models.DateField(verbose_name='Data inicial'),
        ),
    ]
