# Generated by Django 5.1.5 on 2025-01-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_atividade_options_alter_membro_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='feito',
        ),
        migrations.AddField(
            model_name='atividade',
            name='concluido',
            field=models.BooleanField(default=False, verbose_name='Concluído?'),
        ),
    ]
