# Generated by Django 5.1.5 on 2025-01-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_atividade_feito_atividade_concluido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='dt_limite',
            field=models.DateField(verbose_name='Data limite'),
        ),
    ]
