# Generated by Django 5.1.5 on 2025-01-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_membro_inscricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='inscricao',
            field=models.PositiveIntegerField(verbose_name='Inscrição'),
        ),
    ]
