# Generated by Django 5.1.5 on 2025-01-22 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_membro_inscricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atividade',
            options={'ordering': ['dt_limite'], 'verbose_name': 'Atividade', 'verbose_name_plural': 'Atividades'},
        ),
    ]
