# Generated by Django 5.1.5 on 2025-01-22 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_atividade_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atividade',
            options={'ordering': ['dt_limite', 'concluido', 'nome'], 'verbose_name': 'Atividade', 'verbose_name_plural': 'Atividades'},
        ),
        migrations.AlterModelOptions(
            name='membro',
            options={'ordering': ['inscricao', 'nome', 'funcao'], 'verbose_name': 'Membro', 'verbose_name_plural': 'Membros'},
        ),
        migrations.AlterModelOptions(
            name='projeto',
            options={'ordering': ['dt_final', 'nome'], 'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
    ]
