# Generated by Django 5.1.5 on 2025-01-22 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_atividade_options_alter_membro_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipe',
            options={'ordering': ['nome', 'ativa'], 'verbose_name': 'Equipe', 'verbose_name_plural': 'Equipes'},
        ),
        migrations.AddField(
            model_name='equipe',
            name='ativa',
            field=models.BooleanField(default=True, verbose_name='Ativa?'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='projetos', to='core.equipe'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='proejto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='atividades', to='core.projeto'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='membros', to='core.equipe'),
        ),
    ]
