# Generated by Django 5.1.5 on 2025-01-22 19:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_tarefa_delete_atividade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membro',
            options={'ordering': ['nome', 'equipe'], 'verbose_name': 'Membro', 'verbose_name_plural': 'Membros'},
        ),
        migrations.RemoveField(
            model_name='membro',
            name='funcao',
        ),
        migrations.RemoveField(
            model_name='membro',
            name='inscricao',
        ),
        migrations.AddField(
            model_name='membro',
            name='telefone',
            field=models.CharField(blank=True, help_text='(99) 99999-9999', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato (99) 99999-9999', regex='^\\(\\d{2}\\) \\d{5}-\\d{4}$')]),
        ),
        migrations.AddField(
            model_name='projeto',
            name='orcamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Orçamento'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='horas_estimadas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
