# Generated by Django 5.1.5 on 2025-01-15 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Montadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('pais', models.CharField(max_length=128)),
                ('ano_fundacao', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('motorizacao', models.CharField(choices=[('1.0', 'Motor 1.0'), ('1.3', 'Motor 1.3'), ('1.4', 'Motor 1.4'), ('1.6', 'Motor 1.6'), ('2.0', 'Motor 2.0')], max_length=5)),
                ('montadora', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='veiculos', to='core.montadora')),
            ],
        ),
    ]
