# Generated by Django 5.1.5 on 2025-01-15 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Modelo',
            new_name='ModeloVeiculo',
        ),
    ]
