# Generated by Django 5.1.5 on 2025-01-20 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_modelo_modeloveiculo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modeloveiculo',
            options={'ordering': ['montadora__nome', 'nome'], 'verbose_name': 'Modelo de Veículo', 'verbose_name_plural': 'Modelos de Veículos'},
        ),
        migrations.AlterModelOptions(
            name='montadora',
            options={'ordering': ['-ano_fundacao'], 'verbose_name': 'Montadora', 'verbose_name_plural': 'Montadoras'},
        ),
        migrations.AddField(
            model_name='modeloveiculo',
            name='em_producao',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='montadora',
            name='ano_fundacao',
            field=models.PositiveIntegerField(verbose_name='Ano de Fundação'),
        ),
        migrations.AlterField(
            model_name='montadora',
            name='nome',
            field=models.CharField(max_length=128, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='montadora',
            name='pais',
            field=models.CharField(max_length=128, verbose_name='País'),
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7)),
                ('cor', models.CharField(max_length=32)),
                ('ano', models.PositiveIntegerField()),
                ('km_rodados', models.PositiveIntegerField()),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='veiculos', to='core.modeloveiculo')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['modelo__montadora__nome', 'modelo__nome'],
            },
        ),
    ]
